package migrations

import (
	"github.com/flashbots/relayscan/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var migration005SQL = `
CREATE TABLE IF NOT EXISTS ` + vars.TableDataAPIPayloadDeliveredHistory + ` (
	id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at  timestamp NOT NULL default current_timestamp,
	payload_id  bigint NOT NULL,

	relay       text NOT NULL,
	epoch       bigint NOT NULL,
	slot        bigint NOT NULL,

	parent_hash            varchar(66) NOT NULL,
	block_hash             varchar(66) NOT NULL,
	builder_pubkey         varchar(98) NOT NULL,
	proposer_pubkey        varchar(98) NOT NULL,
	proposer_fee_recipient varchar(42) NOT NULL,
	gas_limit              bigint NOT NULL,
	gas_used               bigint NOT NULL,
	value_claimed_wei      NUMERIC(48, 0) NOT NULL,
	value_claimed_eth      NUMERIC(16, 8) NOT NULL,
	num_tx                 int,
	block_number           bigint,
	extra_data    		   text NOT NULL,

	slot_missed	                boolean, 		-- null means not yet checked
	value_check_ok              boolean, 		-- null means not yet checked
	value_check_method          text,  		    -- how value was checked (i.e. blockBalanceDiff)
	value_delivered_wei         NUMERIC(48, 0), -- actually delivered value
	value_delivered_eth         NUMERIC(16, 8), -- actually delivered value
	value_delivered_diff_wei    NUMERIC(48, 0), -- value_delivered - value_claimed
	value_delivered_diff_eth    NUMERIC(16, 8), -- value_delivered - value_claimed
	block_coinbase_addr		    varchar(42),    -- block coinbase address
	block_coinbase_is_proposer  boolean,        -- true if coinbase == proposerFeeRecipient
	coinbase_diff_wei           NUMERIC(48, 0), -- builder value difference
	coinbase_diff_eth           NUMERIC(16, 8), -- builder value difference
	found_onchain               boolean,        -- whether the payload blockhash can be found on chain (at all)
	notes						text,
	num_blob_txs                int,
	num_blobs                   int,
	block_timestamp             timestamp
);

CREATE INDEX IF NOT EXISTS ` + vars.TableDataAPIPayloadDeliveredHistory + `_payload_id_idx ON ` + vars.TableDataAPIPayloadDeliveredHistory + `("payload_id");
CREATE INDEX IF NOT EXISTS ` + vars.TableDataAPIPayloadDeliveredHistory + `_created_at_idx ON ` + vars.TableDataAPIPayloadDeliveredHistory + `("created_at");
CREATE INDEX IF NOT EXISTS ` + vars.TableDataAPIPayloadDeliveredHistory + `_slot_idx ON ` + vars.TableDataAPIPayloadDeliveredHistory + `("slot");
`

var Migration005AddPayloadHistory = &migrate.Migration{
	Id: "005-add-payload-history",
	Up: []string{migration005SQL},

	DisableTransactionUp:   false,
	DisableTransactionDown: true,
}
